# ESTÁGIO 1: Desenvolvimento (Alvo atual)
FROM node:22-alpine AS development
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY prisma ./prisma/
RUN npx prisma generate
COPY . .
CMD ["npm", "run", "start:dev"]

# ESTÁGIO 2: Build (Para produção futura)
FROM node:22-alpine AS build
WORKDIR /usr/src/app
COPY package*.json ./
COPY --from=development /usr/src/app/node_modules ./node_modules
COPY . .
RUN npx prisma generate
RUN npm run build

# ESTÁGIO 3: Produção (Para o servidor final)
# FROM node:20-alpine As production
