/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ViewFormIdRouteImport } from './routes/view.$formId'
import { Route as FormsFormIdRouteImport } from './routes/forms.$formId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewFormIdRoute = ViewFormIdRouteImport.update({
  id: '/view/$formId',
  path: '/view/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsFormIdRoute = FormsFormIdRouteImport.update({
  id: '/forms/$formId',
  path: '/forms/$formId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forms/$formId': typeof FormsFormIdRoute
  '/view/$formId': typeof ViewFormIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forms/$formId': typeof FormsFormIdRoute
  '/view/$formId': typeof ViewFormIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forms/$formId': typeof FormsFormIdRoute
  '/view/$formId': typeof ViewFormIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/forms/$formId' | '/view/$formId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/forms/$formId' | '/view/$formId'
  id: '__root__' | '/' | '/forms/$formId' | '/view/$formId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormsFormIdRoute: typeof FormsFormIdRoute
  ViewFormIdRoute: typeof ViewFormIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/$formId': {
      id: '/view/$formId'
      path: '/view/$formId'
      fullPath: '/view/$formId'
      preLoaderRoute: typeof ViewFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$formId': {
      id: '/forms/$formId'
      path: '/forms/$formId'
      fullPath: '/forms/$formId'
      preLoaderRoute: typeof FormsFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormsFormIdRoute: FormsFormIdRoute,
  ViewFormIdRoute: ViewFormIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
